### ISSUE TITLE
OTP based recommender

### ISSUE THREAD

**Issue by odarriba** [carrify/carrify#10]
The idea is to create an OTP-based process to train and make recommendations.

Ideally, it should be:

- Scalable
- Asynchronous (when possible)
- Independent of the library used

**Comment by odarriba** [comment]
My idea is doing an OTP process (with it's own supervisor) that simply calls a recommendation library (that could be a fake, or a real one) with specific and defined methods (as I discussed with @dreamingechoes , they would be `train` and `recommend` methods.

So that OTP processes could scale as needed, being able even to run in a different machine. Also, a crash in one of those process should not crash the main Carrify process.

**Comment by odarriba** [comment]
Also, remember to add the calls from `recommend` and `track` endpoints to fetch recommendations and train the recommender via these new OTP process.

**Comment by odarriba** [comment]
Pull request created (#14)

**Comment by belaustegui** [comment]
The pull request is merged into the `master` branch :smiley:
