### ISSUE TITLE
Save trackings when possible

### ISSUE THREAD

**Issue by belaustegui** [carrify/carrify#3]
We could use a plug to store trackings accross multiple controllers.

**Comment by odarriba** [comment]
I'm going to add latitude and longitude fields and validations for `Tracking` model, so we can save trackings with `Point` assigned.

**Comment by odarriba** [comment]
I've added a plug to save them (it catch `client_id` and `point_id` or `client_id`, `latitude` and `longitude`).

(More details here: https://github.com/carrify/carrify/blob/e91164464d60bf24113d7f56d87b8013badb4a71/web/controllers/api/v1/client_controller.ex#L91 )

At the moment, it's only used on `recommend` and `close_points` actions of client's API.

**Comment by odarriba** [comment]
Ready and on master for the next deploy. Closing!
