### ISSUE TITLE
Check client_id securely

### ISSUE THREAD

**Issue by odarriba** [carrify/carrify#7]
On client's API, we need to check that received client_id is really a valid one for the token received.

This is important, because otherwise a malicious user will be able to modify other's organisation client's data by assigning tracks related to points that doesn't belongs to it's organisation.

**Comment by odarriba** [comment]
Maybe this can be done in two ways:

1. Check in`Tracking` changeset that `client` and `point` belongs to the same organisation that `api_key`.
2. Checking at controller level that the client_id received on `recommend`, `close_points` and `track` endpoints is valid for the token of the request.

**Comment by odarriba** [comment]
Finally, with check it on the model is enough. In case of validation fail, the plug stops the processing and return a JSON-formatted error explaining what happened.

**Comment by belaustegui** [comment]
Closing since the pull request is now merged.
